  
deploy:
  stage: deploy
  when: manual
  tags:
    - wordpress_deploy
  script:
    - apk add --no-cache docker-compose
    - docker-compose up -d

undeploy:
  stage: deploy
  when: manual
  tags:
    - wordpress_deploy
  script:
    - apk add --no-cache docker-compose
    - docker-compose down

